services: 
  minio:
    image: 'bitnami/minio:latest'
    ports: 
      - '9001:9001'
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
  mysql_server:
    image: mysql
    build: ./db_migration
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    depends_on: 
      - minio
  app:
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MINIO_HOST=${MINIO_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  web:
    build:
      dockerfile: nginx/Dockerfile
      context: ./
    ports:
      - '3000:3000'
    depends_on:
      - app
volumes: 
  db: